syntax on
set re=0
set autoindent
set hlsearch
set ignorecase
set incsearch
set nocompatible
set number
set ruler
set shiftwidth=4
set showmatch
set smartcase
set tabstop=4
set expandtab
set t_Co=256
set background=light

filetype indent plugin on

set rtp+=~/.fzf

let NERDTreeShowHidden=1

map <C-\> :NERDTreeToggle<CR>
nmap <F7> :History<CR>