-- plugins/mkdnflow.lua
return {
  "jakewvincent/mkdnflow.nvim",
  ft = "markdown",
  opts = {
    modules = {
      bib = true,
      yaml = true,
      cmp = false,
      buffers = true,
      conceal = true,
      cursor = true,
      folds = false,
      links = true,
      lists = true,
      maps = true,
      paths = true,
      tables = true,
    },
    filetypes = { md = true, markdown = true },
    create_dirs = true,
    perspective = {
      priority = "root",
      root_tell = "index.md",
      fallback = "current",
    },
    wrap = false,
    links = {
      style = "wiki",
      conceal = true,
      context = 0,
      implicit_extension = nil,
      transform_implicit = false,
      transform_explicit = function(text)
        return text:gsub("%s+", "-"):lower()
      end,
    },
    to_do = {
      symbols = { " ", "-", "x" },
      update_parents = true,
      not_started = " ",
      in_progress = "-",
      complete = "x",
    },
    tables = {
      trim_whitespace = true,
      format_on_move = true,
    },
    mappings = {
      MkdnEnter = { { "n", "v" }, "<CR>" },
      MkdnTab = false,
      MkdnSTab = false,
      MkdnNextLink = { "n", "<Tab>" },
      MkdnPrevLink = { "n", "<S-Tab>" },
      MkdnNextHeading = { "n", "]]" },
      MkdnPrevHeading = { "n", "[[" },
      MkdnGoBack = { "n", "<BS>" },
      MkdnGoForward = { "n", "<Del>" },
      MkdnFollowLink = false,
      MkdnCreateLink = false,
      MkdnCreateLinkFromClipboard = false,
      MkdnDestroyLink = { "n", "<M-CR>" },
      MkdnMoveSource = false,
      MkdnYankAnchorLink = false,
      MkdnYankFileAnchorLink = false,
      MkdnIncreaseHeading = { "n", "+" },
      MkdnDecreaseHeading = { "n", "-" },
      MkdnToggleToDo = { { "n", "v" }, "<C-Space>" },
      MkdnNewListItem = false,
      MkdnNewListItemBelowInsert = { "n", "o" },
      MkdnNewListItemAboveInsert = { "n", "O" },
      MkdnExtendList = false,
      MkdnUpdateNumbering = { "n", "<leader>nn" },
      MkdnTableNextCell = { "i", "<Tab>" },
      MkdnTablePrevCell = { "i", "<S-Tab>" },
      MkdnTableNextRow = false,
      MkdnTablePrevRow = { "i", "<M-CR>" },
      MkdnTableNewRowBelow = { "n", "<leader>ir" },
      MkdnTableNewRowAbove = { "n", "<leader>iR" },
      MkdnTableNewColAfter = { "n", "<leader>ic" },
      MkdnTableNewColBefore = { "n", "<leader>iC" },
      MkdnFoldSection = { "n", "<leader>f" },
      MkdnUnfoldSection = { "n", "<leader>F" },
    },
  },
}
